### ISSUE TITLE
discuss: should we include the memory-storage feature as part of the minimal set?

### ISSUE THREAD

**Issue by echozyr2001** [echozyr2001/CosmoFlow#17]
All of our examples and tests require a storage backend. The problem is, when using the minimal feature set, no storage backend is provided by default. As a result, we repeatedly have to create a custom Storage (e.g., SimpleStorage), which essentially duplicates the functionality of the MemoryStorage provided by the memory-storage feature.

Given this, should we include the memory-storage feature as part of the minimal set?

**Comment by echozyr2001** [comment]
# Feature Configuration Redesign

## Background

We've been discussing whether to include storage-memory in the minimal feature set. After thorough analysis and testing, we've implemented a more intuitive feature hierarchy that better serves different user needs.

## Problem Statement

The original feature design had several issues:

1. Code duplication: Examples and projects repeatedly implemented custom storage (like SimpleStorage) that essentially duplicated MemoryStorage functionality.
2. Poor default experience: New users had to understand feature flags before they could run basic examples.

## Solution: Redesigned Feature Hierarchy

```toml
# Before
default = []
minimal = [] # Core only (confusing for users)
basic = ["storage-memory"] # What users actually wanted from "minimal"
standard = ["storage-memory", "async"]
full = ["storage-full", "async"]

# After  
default = ["basic"] # Point to most common use case
minimal = [] # Truly minimal core (for experts)
basic = ["storage-memory"] # Basic usable configuration
standard = ["storage-memory", "async"] 
full = ["storage-full", "async"]
```

## Code Examples

Before

```
# User had to figure out they needed this
cosmoflow = { version = "0.4", features = ["storage-memory"] }
```

After

```
# Just works
cosmoflow = "0.4"
```

For Expert Users

```
# Still available for those who need it
cosmoflow = { version = "0.4", default-features = false, features = ["minimal"] }
```
